// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAztnH2lzN4OJdvTgC9FSfZ6eocR6SFdF0',
    appId: '1:215341321165:web:4960582edc0b7ac3849284',
    messagingSenderId: '215341321165',
    projectId: 'gativa',
    authDomain: 'gativa.firebaseapp.com',
    storageBucket: 'gativa.firebasestorage.app',
    measurementId: 'G-KR5HRYRJEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Vz0f19dVGJPTVabmut8HLZNzsXDLJkw',
    appId: '1:215341321165:android:0f5ff541b15fcbc2849284',
    messagingSenderId: '215341321165',
    projectId: 'gativa',
    storageBucket: 'gativa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACPKS-eyQ-QUwdubAEpTP60ntsyOOSha0',
    appId: '1:215341321165:ios:453e40c6e35cf902849284',
    messagingSenderId: '215341321165',
    projectId: 'gativa',
    storageBucket: 'gativa.firebasestorage.app',
    iosBundleId: 'com.example.garda',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACPKS-eyQ-QUwdubAEpTP60ntsyOOSha0',
    appId: '1:215341321165:ios:453e40c6e35cf902849284',
    messagingSenderId: '215341321165',
    projectId: 'gativa',
    storageBucket: 'gativa.firebasestorage.app',
    iosBundleId: 'com.example.garda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAztnH2lzN4OJdvTgC9FSfZ6eocR6SFdF0',
    appId: '1:215341321165:web:74cef1f6e5e6781f849284',
    messagingSenderId: '215341321165',
    projectId: 'gativa',
    authDomain: 'gativa.firebaseapp.com',
    storageBucket: 'gativa.firebasestorage.app',
    measurementId: 'G-NSWMG9HYFZ',
  );
}
