// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnZBzKo1GlCN3rh2lQNJFWE3jVuhzrB4s',
    appId: '1:164136426035:web:75caf21dbb9675ecfa6146',
    messagingSenderId: '164136426035',
    projectId: 'garda-5a54e',
    authDomain: 'garda-5a54e.firebaseapp.com',
    storageBucket: 'garda-5a54e.firebasestorage.app',
    measurementId: 'G-GLXF23WRXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6wnl-SRgx_QAzik-w0cU0N8Bo41bLpb4',
    appId: '1:164136426035:android:98343032da436cc7fa6146',
    messagingSenderId: '164136426035',
    projectId: 'garda-5a54e',
    storageBucket: 'garda-5a54e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh16Y5_cEkBocC4sG-W_wh1x49QhLjLm0',
    appId: '1:164136426035:ios:3325aab26fc32283fa6146',
    messagingSenderId: '164136426035',
    projectId: 'garda-5a54e',
    storageBucket: 'garda-5a54e.firebasestorage.app',
    iosBundleId: 'com.example.garda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh16Y5_cEkBocC4sG-W_wh1x49QhLjLm0',
    appId: '1:164136426035:ios:3325aab26fc32283fa6146',
    messagingSenderId: '164136426035',
    projectId: 'garda-5a54e',
    storageBucket: 'garda-5a54e.firebasestorage.app',
    iosBundleId: 'com.example.garda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnZBzKo1GlCN3rh2lQNJFWE3jVuhzrB4s',
    appId: '1:164136426035:web:a7a858e9fe84e5f7fa6146',
    messagingSenderId: '164136426035',
    projectId: 'garda-5a54e',
    authDomain: 'garda-5a54e.firebaseapp.com',
    storageBucket: 'garda-5a54e.firebasestorage.app',
    measurementId: 'G-SR1SDJTVN0',
  );
}
